In [1]:
import numpy as np

In [2]:
a = np.array([1,2,3], dtype='int32')#This code is used to print a single dimensional array
print(a)

[1 2 3]


In [3]:
b = np.array([[9.0,8.0,7.0],[6.0,5.0,4.0]])#This code is used to print two dimensional array
print(b)

[[9. 8. 7.]
 [6. 5. 4.]]


In [4]:
# Get Dimension
a.ndim #This code is used to print dimension of the given array

1

In [5]:
b.ndim #This code is used to print dimension of the given array

2

In [7]:
# Get Type
a.dtype #It shows the datatype size in which the array is stored

dtype('int32')

In [8]:
# Get Size
a.itemsize #It shows how many bytes the variable occupy

4

In [9]:
# Get total size
a.nbytes #It shows the total size occupied by the variable

12

In [10]:
# Get number of elements
a.size

3

In [11]:
a = np.array([[1,2,3,5,7],[9,11,13,15,17]])
print(a)

[[ 1  2  3  5  7]
 [ 9 11 13 15 17]]


In [12]:
a[1,4]#used to find specific element[r,c]

17

In [13]:
print(a[0, :]) #used to find elements in a particlar row

[1 2 3 5 7]


In [14]:
print(a[:, 2]) #used to find elements in a particlar column

[ 3 13]


In [19]:
dt = np.dtype([('age',np.int8)]) #it uses file name to get the content in a particular column
a = np.array([(10,),(20,),(30,)], dtype = dt) 
print (a['age'])

[10 20 30]


In [20]:
a = np.array([[1,2,3],[4,5,6]]) 
a.shape = (3,2) #this resizes the array
print (a)

[[1 2]
 [3 4]
 [5 6]]


In [21]:
a = np.arange(24) 
print (a) #it prints the output which are evenly spaced

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23]


In [23]:
a = np.arange(24) 
b = a.reshape(2,4,3) 
print (b)#this code reshapes the one dimensional array into three dimensional array

[[[ 0  1  2]
  [ 3  4  5]
  [ 6  7  8]
  [ 9 10 11]]

 [[12 13 14]
  [15 16 17]
  [18 19 20]
  [21 22 23]]]


In [24]:
a= np.array([1,2,3])
print(a.min())# used to find minimum value in the array
print(a.max())# used to find maximum value in the array
print(a.sum())# used to find the sum of values in the array

1
3
6


In [25]:
a= np.array([(1,2,3),(3,4,5)])
print(a.sum(axis=0))# sum of all values in the same columns

[4 6 8]


In [26]:
a=np.array([(1,2,3),(3,4,5,)])
print(np.sqrt(a))#Square Root of the variables in the array
print(np.std(a))#Standard Deviation of the array

[[1.         1.41421356 1.73205081]
 [1.73205081 2.         2.23606798]]
1.2909944487358056


In [27]:
x= np.array([(1,2,3),(3,4,5)])
y= np.array([(1,2,3),(3,4,5)])
print(x-y)#subtraction of variables in an array
print(x*y)#multiplication of variables in an array
print(x/y)#division of variables in an array

[[0 0 0]
 [0 0 0]]
[[ 1  4  9]
 [ 9 16 25]]
[[1. 1. 1.]
 [1. 1. 1.]]


In [28]:
x= np.array([(1,2,3),(3,4,5)])
print(x.ravel())#it converts one numpy array into a single column

[1 2 3 3 4 5]


In [29]:
a=np.linspace(1,3,10)
print(a)#it returns evenly spaced numbers over a specified interval

[1.         1.22222222 1.44444444 1.66666667 1.88888889 2.11111111
 2.33333333 2.55555556 2.77777778 3.        ]


In [38]:
f = np.array([1,2])
g = np.array([4,5])
np.dot(f, g)#it returns the dot product of the two array

14

In [36]:
a = np.matrix('[1 , 2; 3, 4]')
transpose = a.transpose()    
print(transpose)#returns the transpose of the matrix

[[1 3]
 [2 4]]


In [37]:
a = np.matrix('[1, 2; 3, 4]')
trace = a.trace()   
print(trace)

[[5]]


In [40]:
a = np.matrix('[1, 2; 3, 4]')
diagonal = a.diagonal()   
print(diagonal)#returns the diagonal of a matrix

[[1 4]]


In [43]:
rank = np.array([[1,2,3],[4,5,6],[7,8,9]])
np.linalg.matrix_rank(rank)#returns the rank of the matrix

2